language: go

go:
  - 1.3
  - 1.4
  - tip


# we're in $HOME/gopath/src/github.com/tp/ziputil
install:
  - cd ../../../
  - pwd
  - mkdir timm.io
  - mv github.com/tp/ziputil timm.io/

script: go test -v ./...